[ERROR] Error running: python3 /home/kingusmao/t2-integradora/blocks-world/fd/fast-downward.py /home/kingusmao/t2-integradora/blocks-world/domain.pddl /home/kingusmao/t2-integradora/blocks-world/problem.pddl --landmarks "lm=lm_exhaust(reasonable_orders=false, only_causal_landmarks=false, disjunctive_landmarks=false, conjunctive_landmarks=true, no_orders=false)" --heuristic "hlm=lmcount(lm)" --search "astar(lmcut())" > /home/kingusmao/t2-integradora/blocks-world/output.txt
